[package]
name = "travel-time-rs"
version = "0.1.0"
authors = ["Daniel Parker <danpker@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.7"
serde = "1.0.84"
serde_json = "1.0.34"
serde_derive = "1.0.84"
